stages:
  - test

test:
  stage: test
  script:
  - apt-get update -qy
  - apt-get install -y python-dev python-pip
  - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
  - poetry install
  - poetry run mypy soji
  - poetry run pytest -v

