version: 1
disable_existing_loggers: no

filters:
    elapsed_filter:
        (): seiso.common.logging.ElapsedFilter

formatters:
    console_format:
        format: "%(elapsed)s %(levelname)s %(message)s"
    file_format:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
    console_handler:
        class: logging.StreamHandler
        level: INFO
        formatter: console_format
        stream: ext://sys.stdout
        filters: [elapsed_filter]

    debug_log_handler:
        class: logging.handlers.TimedRotatingFileHandler
        when: midnight
        level: DEBUG
        formatter: file_format
        filename: logs/debug.log
        encoding: utf8

    bare_log_handler:
        class: logging.handlers.TimedRotatingFileHandler
        when: midnight
        level: INFO
        formatter: file_format
        filename: logs/bare.log
        encoding: utf8

    promus_log_handler:
        class: logging.handlers.TimedRotatingFileHandler
        when: midnight
        level: INFO
        formatter: file_format
        filename: logs/promus.log
        encoding: utf8

root:
    level: NOTSET
    handlers: [console_handler, debug_log_handler]

loggers:
    soji.services.bare:
        level: DEBUG
        handlers: [bare_log_handler]
    soji.common.bare_record:
        level: DEBUG
        handlers: [bare_log_handler]
    soji.services.promus:
        level: DEBUG
        handlers: [promus_log_handler]
