version: 1
disable_existing_loggers: no

filters:
    elapsed_filter:
        (): seiso.common.logging.ElapsedFilter

formatters:
    console_format:
        format: "%(elapsed)s %(levelname)s %(message)s"
    file_format:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
    console_handler:
        class: logging.StreamHandler
        level: INFO
        formatter: console_format
        stream: ext://sys.stdout
        filters: [elapsed_filter]

    debug_log_handler:
        class: logging.handlers.TimedRotatingFileHandler
        when: midnight
        level: DEBUG
        formatter: file_format
        filename: {{log-path}}/debug.log
        encoding: utf8

    bare_log_handler:
        class: logging.handlers.TimedRotatingFileHandler
        when: midnight
        level: INFO
        formatter: file_format
        filename: {{log-path}}/bare.log
        encoding: utf8

    promus_update_log_handler:
        class: logging.handlers.TimedRotatingFileHandler
        when: midnight
        level: INFO
        formatter: file_format
        filename: {{log-path}}/promus_updates.log
        encoding: utf8

    oai_log_handler:
        class: logging.handlers.TimedRotatingFileHandler
        when: W0
        level: INFO
        formatter: file_format
        filename: {{log-path}}/oai.log
        encoding: utf8

root:
    level: NOTSET
    handlers: [console_handler, debug_log_handler]

loggers:
    seiso.services.bare:
        level: DEBUG
        handlers: [bare_log_handler]
    seiso.common.bare_record:
        level: DEBUG
        handlers: [bare_log_handler]
    promus_update_logger:
        level: DEBUG
        handlers: [promus_update_log_handler]
    seiso.services.oai:
        level: INFO
        handlers: [oai_log_handler]
